# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'db_table': 'tb_brand',
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_cate', to='goods.Brand', verbose_name='外键关联')),
            ],
            options={
                'db_table': 'tb_cate',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goods_size', models.CharField(max_length=50, verbose_name='商品规格')),
                ('goods_count', models.CharField(max_length=100, verbose_name='商品数量')),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate_goods', to='goods.Cate', verbose_name='外键关联')),
            ],
            options={
                'db_table': 'tb_goods',
            },
        ),
    ]
